services:
  - type: web
    name: alexflow # назва проєкту не принципова, можна не змінювати, і так все працює
    env: python
    plan: free                
    
    buildCommand: ./build.sh
    startCommand: gunicorn Rest.wsgi:application --log-level info
    
    envVars:
      - key: SECRET_KEY
        generateValue: true
        sync: false
      
      - key: DEBUG
        value: "False"
      
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      
      - key: PYTHON_VERSION
        value: "3.14"        

    # підключення бази даних
    databases:
      - name: my-django-db
        databaseName: mydb
        user: myuser
        plan: free
